object RenderForm: TRenderForm
  Left = 217
  Top = 78
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'RenderForm'
  ClientHeight = 600
  ClientWidth = 800
  Color = clBackground
  DefaultMonitor = dmMainForm
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poDesigned
  Scaled = False
  PixelsPerInch = 120
  TextHeight = 16
end
